---
# tasks file for orders

- name: setup the code
  ansible.builtin.include_role: common

- name: Install Java, Maven
  ansible.builtin.dnf:
    name:
      - java-21-openjdk
      - java-21-openjdk-devel
      - maven
      - unzip


- name: build code
  ansible.builtin.shell: |
    mvn clean package -DskipTests
    cp target/{{ component_name }}.jar /app/{{ component_name }}.jar
  args:
    chdir: /app

- name: restart oders service
  ansible.builtin.systemd_service:
    name: "{{ component_name }}"
    state: restarted
    daemon_reload: true
    enabled: yes
