---
# tasks file for orders

- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: main

- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: java


- name: build code
  ansible.builtin.shell: |
    mvn clean package -DskipTests
    cp target/{{ component_name }}.jar /app/{{ component_name }}.jar
  args:
    chdir: /app

- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: systemd