---
# tasks file for "{{ component_name }}"
- name: setup the code
  ansible.builtin.include_role: 
    name: common
    tasks_from: main

- name: Install Java
  ansible.builtin.include_role: 
    name: common
    tasks_from: java

- name: Wait for MySQL to be ready
  ansible.builtin.wait_for:
    host: "mysql-{{ env }}.naresh-training.online"
    port: 3306
    state: started
    delay: 10
    timeout: 300


- name: setup datbase
  ansible.builtin.shell: |
    mysql -h mysql-{{ env }}.naresh-training.online -u root -pRoboShop@1 < /appdb/schema.sql
    mysql -h mysql-{{ env }}.naresh-training.online -u root -pRoboShop@1 < /app/db/app-user.sql
    mvn clean package -DskipTests
    cp target/{{ component_name }}.jar /app/{{ component_name }}.jar
  args:
    chdir: /app

- name: setup the code
  ansible.builtin.include_role: 
    name: common
    tasks_from: systemd