---
# tasks file for shipping
- name: install java, maven
  ansible.builtin.dnf:
    name:
      - java-21-openjdk
      - java-21-openjdk-devel
      - maven
      - mysql8.4
      - unzip

- name: copy service file
  ansible.builtin.copy:
    src: shipping.service
    dest: /etc/systemd/system/shipping.service

- name: create user
  ansible.builtin.user:
    name: appuser
    shell: /bin/false

- name: create app directory
  ansible.builtin.file:
    path: /app
    owner: appuser
    group: appuser
    mode: "0770"
    state: directory

- name: download code & unzip
  ansible.builtin.unarchive:
    src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/shipping.zip
    dest: /app
    remote_src: yes

- name: setup datbase
  ansible.builtin.shell: |
    mysql -h 10.0.19.213 -u root -pRoboShop@1 < db/schema.sql
    mysql -h 10.0.19.213 -u root -pRoboShop@1 < db/app-user.sql
    mvn clean package -DskipTests
    cp target/shipping.jar /app/shipping.jar
  args:
    chdir: /app

- name: restart shipping service
  ansible.builtin.systemd_service:
    name: shipping
    state: restarted
    enabled: yes
    daemon_reload: true
