---
# tasks file for "{{ component_name }}"
- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: main

- name: Install Java
  ansible.builtin.include_role: common
  tasks_from: java

- name: setup datbase
  ansible.builtin.shell: |
    mysql -h 10.0.27.103 -u root -pRoboShop@1 < db/schema.sql
    mysql -h 10.0.27.103 -u root -pRoboShop@1 < db/app-user.sql
    mvn clean package -DskipTests
    cp target/{{ component_name }}.jar /app/{{ component_name }}.jar
  args:
    chdir: /app

- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: systemd