front_end ansible_host=10.0.27.114 ansible_user=ec2-user
mysql_server ansible_host=10.0.23.162 ansible_user=ec2-user
catalogue_server ansible_host=10.0.20.98 ansible_user=ec2-user
[web]
front_end
[mysql]
mysql_server
[catalogue]
catalogue_server