front_end ansible_host=10.0.21.0 ansible_user=ec2-user
mysql_server ansible_host=10.0.21.6 ansible_user=ec2-user
catalogue_server ansible_host=10.0.21.6 ansible_user=ec2-user
[web]
front_end
[mysql]
mysql_server
[catalogue]
catalogue_server