front_end ansible_host=10.0.24.171 ansible_user=ec2-user
mysql_server ansible_host=10.0.21.205 ansible_user=ec2-user
catalogue_server ansible_host=10.0.31.103 ansible_user=ec2-user
[web]
front_end
[mysql]
mysql_server
[catalogue]
catalogue_server