- name: setup mongodb server
  hosts: mongo
  become: yes
  gather_facts: no
  tasks:
    - name: copy mongo repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongodb-org-7.0.repo
    
    - name: Install mongodb
      ansible.builtin.dnf:
        name: mongodb-org

    - name: update bindIP address
      ansible.builtin.shell: |
        sed -i "s/bindIp: 127.0.0.1/bindIp: 0.0.0.0/" /etc/mongod.conf

    - name: restart service
      ansible.builtin.systemd_service:
         state: restarted
         enabled: yes
         daemon_reload: true
         name: mongod
