- name: Disable Security Settings
  hosts: all
  become: yes
  tasks:

    - name: Permanently Disable SELinux
      ansible.builtin.replace:
        path: /etc/selinux/config
        regexp: 'SELINUX=enforcing'
        replace: 'SELINUX=disabled'

    - name: Disable SELinux for current session
      ansible.builtin.shell: setenforce 0
      ignore_errors: yes