- name: setup user service
  hosts: user
  become: yes
  gather_facts: no
  tasks:
    - name: install nodejs
      ansible.builtin.shell: |
        curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
        dnf install -y nodejs
        dnf install -y unzip

    - name: copy user service file
      ansible.buitin.copy: 
        src: user.service
        dest: /etc/systemd/system/user.service
        

    - name: create user
      ansible.builtin.user:
        name: appuser
        shell: /bin/false
    - name: create app directory
      ansible.builtin.file:
        path: /app
        owner: appuser
        group: appuser
        mode: '0770'
        state: directory

    - name: download & unzip code
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/user.zip
        dest: /app
        remote_src: yes

    - name: install dependencies
      ansible.builtin.shell: npm install --production
      args:
        chdir: /app
    
    - name: restart user service
      ansible.builtin.systemd_service:
        name: user
        state: restarted
        enabled: yes
        deamon_reload: true

