---
# tasks file for user
- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: main

- name: Install NodeJs
  ansible.builtin.include_role: common
  tasks_from: modejs


- name: install dependencies
  ansible.builtin.shell: npm install --production
  args:
    chdir: /app

- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: systemd
