---
# tasks file for "{{ component_name }}"
- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: main

- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: python

- name: download dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app

- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: systemd
