---
- name: Create swap file in /var (Required for 1GB RAM)
  ansible.builtin.shell: |
    # Remove any failed/partial files from previous attempts
    swapoff /swapfile || true
    rm -f /swapfile
    rm -f /var/swapfile
    
    # Create 1GB swap in the partition with space (/var)
    fallocate -l 1G /var/swapfile
    chmod 600 /var/swapfile
    mkswap /var/swapfile
    swapon /var/swapfile
  args:
    creates: /var/swapfile
    
# tasks file for mysql
- name: install mysql server
  ansible.builtin.dnf:
    name: mysql8.4-server
    state: present

- name: Restart mysqld service
  ansible.builtin.systemd_service:
    state: restarted
    enabled: yes
    daemon_reload: true
    name: mysqld
  register: result
  until: result is succeeded
  retries: 5
  delay: 10

- name: set root password
  ansible.builtin.shell: |
    mysql -u root -pRoboShop@1 -e "status" &>/dev/null
    if [ $? -ne 0 ]; then
      # If we reach here, password is not set or is different. 
      # On RHEL/AlmaLinux, mysql_secure_installation logic or direct SQL works:
      mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';FLUSH PRIVILEGES;"
    fi
  ignore_errors: true