---
# tasks file for catalogue
- name: install go
  ansible.builtin.dnf:
    name:
      - golang
      - git
      - mysql8.4
      - unzip

- name: copy service file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Add the app user
  ansible.builtin.user:
    name: appuser
    shell: /bin/false

- name: create app directory
  ansible.builtin.file:
    path: /app
    owner: appuser
    group: appuser
    mode: "0770"
    state: directory

- name: download & unzip code
  ansible.builtin.unarchive:
    src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/catalogue.zip
    dest: /app
    remote_src: yes

- name: Load schema
  ansible.builtin.shell: mysql -h 10.0.27.103 -u root -pRoboShop@1 < db/schema.sql
  args:
    chdir: /app

- name: Create catalogue DB user
  ansible.builtin.shell: mysql -h 10.0.27.103 -u root -pRoboShop@1 < db/app-user.sql
  args:
    chdir: /app

- name: Load master data
  ansible.builtin.shell: mysql -h 10.0.27.103 -u root -pRoboShop@1 catalogue < db/master-data.sql
  args:
    chdir: /app

- name: build go application
  ansible.builtin.shell: |
    go mod tidy
    CGO_ENABLED=0 go build -o /app/catalogue .
  args:
    chdir: /app

- name: Restart mysqld service
  ansible.builtin.systemd_service:
    state: restarted
    enabled: yes
    daemon_reload: true
    name: catalogue
