---
# tasks file for cart
- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: main

- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: python


- name: database schema load
  ansible.builtin.shell: |
    mysql -h 10.0.27.103 -u root -pRoboShop@1 < db/schema.sql
  args:
    chdir: /app

- name: "{{ component_name }} db user creation"
  ansible.builtin.shell: |
    mysql -h 10.0.27.103 -u root -pRoboShop@1 < db/app-user.sql
  args:
    chdir: /app

- name: download dependcies
  ansible.builtin.shell: |
    pip3 install -r /app/requirements.txt cryptography
  args:
    chdir: /app

- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: systemd
