---
# tasks file for cart
    - name: install python
      ansible.builtin.dnf:
        name:
          - python3 
          - python3-pip
          - mysql8.4
          - unzip
    - name: copy service file
      ansible.builtin.copy:
        src: ratings.service
        dest: /etc/systemd/system/ratings.service

    - name: create app user
      ansible.builtin.user:
        name: appuser
        shell: /bin/false

    - name: create app directory
      ansible.builtin.file:
        path: /app
        owner: appuser
        group: appuser
        mode: "0770"
        state: directory

    - name: download code & unzip
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/ratings.zip
        dest: /app
        remote_src: yes

    - name: database schema load
      ansible.builtin.shell: |
        mysql -h 10.0.27.103 -u root -pRoboShop@1 < db/schema.sql
      args:
        chdir: /app

    - name: ratings db user creation
      ansible.builtin.shell: |
        mysql -h 10.0.27.103 -u root -pRoboShop@1 < db/app-user.sql
      args:
        chdir: /app

    - name: download dependcies
      ansible.builtin.shell: |
        pip3 install -r /app/requirements.txt cryptography
      args:
        chdir: /app

    - name: restart ratings service
      ansible.builtin.systemd_service:
        name: ratings
        state: restarted
        enabled: yes
        daemon_reload: true        
