---
# tasks file for cart
- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: main

- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: nodejs

- name: install dependencies
  ansible.builtin.shell: npm install --production
  args:
    chdir: /app

- name: setup the code
  ansible.builtin.include_role: common
  tasks_from: systemd
